update asset.json
albertov19/xcmTools pull request #2
Opened 2024-01-25 09:07 UTC by wuzhong-papermoon

Update information in asset.json

2024-01-25 10:55 UTC, albertov19 requested changes
Looking good, left some comments

2024-01-25 10:55 UTC, albertov19 commented on assets.json
>          "name": "Moonriver",
Hey as for the name. I would indeed add something that references that this token is Composable Finance Moonriver IBC for example

2024-01-25 10:55 UTC, albertov19 commented on assets.json
>          "name": "Celestia",
Composable Finance Celestia IBC

2024-01-25 10:55 UTC, albertov19 commented on assets.json
>          "name": "Inter Stable Token",
This is another Composable one right?

2024-01-25 10:55 UTC, albertov19 commented on assets.json
>          "name": "Agoric",
Composoable

2024-01-25 10:55 UTC, albertov19 commented on assets.json
>          "name": "Cosmos Hub",
Composable

2024-01-25 10:55 UTC, albertov19 commented on assets.json
>          "name": "Picasso",
Composable

2024-01-25 10:55 UTC, albertov19 commented on assets.json
>          "name": "PARA",
```suggestion
        "name": "Parallel Finance",
```

2024-01-25 10:55 UTC, albertov19 commented on assets.json
>          "name": "BNC",
```suggestion
        "name": "Bifrost",
```

2024-01-25 10:55 UTC, albertov19 commented on assets.json
>          "name": "xcDOT",
```suggestion
        "name": "Polkadot",
```

2024-01-25 10:55 UTC, albertov19 commented on assets.json
>          "name": "aSEED",
```suggestion
        "name": "Acala aSEED",
```

2024-01-25 10:55 UTC, albertov19 commented on assets.json
>          "name": "Acala Dollar",
```suggestion
        "name": "Acala aSEED",
```

2024-01-25 10:55 UTC, albertov19 commented on assets.json
>      "moonbase": [
I would remove all Moonbase ones and just leave `xcUNIT` for testing

2024-01-29 09:50 UTC, wuzhong-papermoon commented on assets.json
>          "name": "Moonriver",
Does this work?
```suggestion
        "name": "Composable Finance Moonriver IBC",
```

2024-01-29 09:50 UTC, wuzhong-papermoon commented on assets.json
>          "name": "Celestia",
```suggestion
        "name": "Composable Finance Celestia IBC",
```

2024-01-29 09:50 UTC, wuzhong-papermoon commented on assets.json
>          "name": "Inter Stable Token",
Yes!
```suggestion
        "name": "Composable Finance Inter Stable Token IBC",
```

2024-01-29 09:50 UTC, wuzhong-papermoon commented on assets.json
>          "name": "Agoric",
```suggestion
        "name": "Composable Finance Agoric IBC",
```

2024-01-29 09:50 UTC, wuzhong-papermoon commented on assets.json
>          "name": "Cosmos Hub",
```suggestion
        "name": "Composable Finance Cosmos Hub IBC",
```

2024-01-29 09:50 UTC, wuzhong-papermoon commented on assets.json
>          "name": "Picasso",
```suggestion
        "name": "Composable Finance Picasso IBC",
```

2024-01-29 09:50 UTC, wuzhong-papermoon commented on assets.json
> +      }
```suggestion
      {
        "name": "xcUNIT",
        "assetID": "42259045809535163221576417993425387648",
        "price": 0
      }
```

2024-01-29 10:32 UTC, wuzhong-papermoon commented on assets.json
> +        "price": 0.00099
```suggestion
        "price": 0.0009651
```

2024-01-29 10:45 UTC, albertov19 approved these changes
LGTM

2024-01-29 10:45 UTC, merged